### ISSUE TITLE
about the C3D model size

### ISSUE THREAD

**Issue by bairw660606** [facebookresearch/VMZ#103]
Hi, 
   thanks for your work. it really help me! but I have a question.
   I look at the number of the C3D model parameter is 64.9M in the Model zoo, but in the Pseudo-3D paper , it's 321M . Why? I'm so confused.

**Comment by bairw660606** [comment]
it's backbone is Resnet-34? right?

**Comment by leemengxing** [comment]
Although it is not related to the question, I still want to ask you to give a C3D link, the model_zoo link is invalid. Thank you for your help, my email is leemengxing93@gmail.com.

**Comment by 123liluky** [comment]
@bairw660606  @leemengxing Could you share your Installation steps before training? I am confused with Installation-guide. Thank you.

**Comment by leemengxing** [comment]
what problem do you meet with installation-guide? @123liluky

**Comment by dutran** [comment]
All dropbox links for C3D models are here https://github.com/facebookresearch/VMZ/blob/master/c2/tutorials/model_zoo.md and I checked, they are working fine.
