### ISSUE TITLE
Script for training  ip-csn-152 from scratch on Kinetics

### ISSUE THREAD

**Issue by huangjun12** [facebookresearch/VMZ#108]
hi, how to write the script(.sh file)  for training  ip-csn-152 from scratch on Kinetics?
I'm little confused with these optional args...

**Comment by 123liluky** [comment]
@huangjun12  Could you share your Installation steps before training? I am confused with Installation-guide. Thank you.

**Comment by huangjun12** [comment]
> @huangjun12 Could you share your Installation steps before training? I am confused with Installation-guide. Thank you.

I also followed the Installation-guide, so what problem in your case? wish i can help you...

**Comment by 123liluky** [comment]
can not find opencv-3.4.0.zip
![image](https://user-images.githubusercontent.com/20832778/75925016-e94be700-5ea2-11ea-8f8c-1b8fd117352f.png)

**Comment by 123liluky** [comment]
@huangjun12 Could you please add my QQ to talk about this, qq:1240307423

**Comment by dutran** [comment]
we used the distributed training and the hyper-parameters provided in the paper.

**Comment by huangjun12** [comment]
> we used the distributed training and the hyper-parameters provided in the paper.

Actually, the hyper-parameters in the paper is not so clear ...
