### ISSUE TITLE
Do we have tutorial or coding tutorial on how to use VMZ?

### ISSUE THREAD

**Issue by JonathanSum** [facebookresearch/VMZ#121]
If possible, do we have coding tutorial on how to use the video training in pytorch? I know the torch.vision.io does this, but there is no tutorial.

**Comment by bjuncek** [comment]
at the moment there are `train_net` and `test_net` tools for pytorch, but the reference to use them is baked in the documentation. 

What do you envision as a tutorial? something like a jupyter notebook? 

Cheers, 
Bruno

**Comment by JonathanSum** [comment]
Thank you for answering. Yes, I hope we can have something like a jupyter notebook.

**Comment by paden118** [comment]
Does any tutorial for using the PyTorch version now?

**Comment by paden118** [comment]
> at the moment there are `train_net` and `test_net` tools for pytorch, but the reference to use them is baked in the documentation.
> 
> What do you envision as a tutorial? something like a jupyter notebook?
> 
> Cheers, Bruno

Does any tutorial for using the PyTorch version now?
