### ISSUE TITLE
can I download IG65M dataset?

### ISSUE THREAD

**Issue by pritamqu** [facebookresearch/VMZ#132]
I tried looking for the IG65M dataset to download and pre-train my model, could you please let me know if it's public or just for internal use at Facebook?
sorry for a naive question!

referred from here: https://github.com/moabitcoin/ig65m-pytorch/issues/42#issuecomment-878187827

**Comment by dragen1860** [comment]
+1

**Comment by dutran** [comment]
unfortunately, we can release the models only.
