### ISSUE TITLE
Feature vector dimensions 

### ISSUE THREAD

**Issue by nayyeraafaq** [facebookresearch/VMZ#26]
Hi everyone, 
The paper says that dimensions of fc layer is 400 for kinetics and 512 for pooling. Is that the right ? Does any model offers 4096 dimensions feature vector extraction ? Can we perform feature extraction of own videos on this network for other applications use? 
Thanks

**Comment by dutran** [comment]
Yes, the output of R(2+1)D-18 and -34 model provides feature at pool-5 is 512-dim, I plan to release soon a  R(2+1)D-50 with 2048-dim feature output.

**Comment by think-high** [comment]
Wow. This sounds good. Even I would be looking forward to the R(2+1)D-50 with 2048 feature output.

**Comment by alexanderfrey** [comment]
Any updates on this ?

**Comment by dutran** [comment]
new, deeper models are released, feel free to give it a try, thanks!
