### ISSUE TITLE
Pre-trained models on Sports 1M dataset

### ISSUE THREAD

**Issue by cdeepakroy** [facebookresearch/VMZ#28]
Kudos to the developers of this great repo!

It would be great if you could release the pre-trained models of C3D, R3D and R(2+1)D on Sports 1M dataset whose results are reported in Table 4 of your paper [A closer look at spatio-temporal convolutions for action recognition](https://arxiv.org/abs/1711.11248). I am trying to benchmark these models on a custom dataset that is more closer to Sports 1M than Kinetics.

**Comment by dutran** [comment]
Yes, we should be able to release those models on Sports-1M, I'll keep you posted here.

**Comment by nimit1997** [comment]
any updates yet as to when you will release those models on Sports-1M ?

**Comment by dutran** [comment]
Sports1M pre-trained models are released with also IG65M.

**Comment by jaypatravali** [comment]
@dutran  the Sport1M pretrained model with IG65M I find only the 8 or 32 frame pretrained weights. Do you also have 16 frame input model?

**Comment by ykn96** [comment]
@dutran I know this is quite the old post. I am unable to find the link for the Sports1M pre-trained model. Could you please point me in the right direction? 

@jaypatravali  @nimit1997  @cdeepakroy

**Comment by dutran** [comment]
some models are here https://github.com/facebookresearch/VMZ/tree/main/c2#readme

**Comment by ykn96** [comment]
@dutran thank you so much for that!
