### ISSUE TITLE
ImportError: No module named models.model_builder

### ISSUE THREAD

**Issue by 953585130** [facebookresearch/VMZ#39]
Hi，
I have built the environment according to the tutorial. I want to do a test with two small videos. I created the lmdb database through the script, but when I executed the script to extract the features, I made an error. I tried to modify the path and still failed. Solve, hope to get your help, thanks.

ThinkStation:~/R2Plus1D-master$ sh scripts/extract_feature_myvideos.sh
Traceback (most recent call last):
  File "tools/extract_features.py", line 21, in <module>
    import models.model_builder as model_builder
ImportError: No module named models.model_builder

**Comment by CHJoanna** [comment]
Do ```export PYTHONPATH=$PYTHONPATH:`pwd`/lib``` under root directory.
(See tutorials/faq)

**Comment by dutran** [comment]
@953585130 does it work for you?

**Comment by 953585130** [comment]
> 做`` export PYTHONPATH=$PYTHONPATH:`pwd`/lib ``根目录下。
> （参见教程/常见问题解答）

**Comment by 953585130** [comment]
@dutran Since it was more urgent at the time, I copied the models and utils in the lib folder to the tools folder and then executed it. At the beginning of the tutorial, I said that I tried to test on the cpu. However, I can't perform feature extraction on the cpu. I am trying gpu.

**Comment by 953585130** [comment]
@CHJoanna Thank you for your reply! Since it was more urgent at the time, I copied the models and utils in the lib folder to the tools folder and then executed it. At the beginning of the tutorial, I said that I tried to test on the cpu. However, I can't perform feature extraction on the cpu. I am trying gpu.I can try this method on gpu.
