### ISSUE TITLE
Reg : Testing Model

### ISSUE THREAD

**Issue by ChaitanyaBoggavarapu** [facebookresearch/VMZ#56]
I am trying to just use pretrained models to test. How do I generate clips for test data is that using ffmpeg or clips are generated in test_net.py?

**Comment by ChaitanyaBoggavarapu** [comment]
![screenshot from 2018-12-10 13-35-51](https://user-images.githubusercontent.com/26795676/49760140-dedf7500-fc80-11e8-8209-aabe357e06ae.png)

this is the output which i got but not sure I am doing it right. I used r2.5d_d18_l16.pkl model

**Comment by dutran** [comment]
Check out this https://github.com/facebookresearch/VMZ/tree/master/tutorials

**Comment by ChaitanyaBoggavarapu** [comment]
Thanks...what would be the ideal test size to test(I am running using CPU)
