### ISSUE TITLE
Why there is no maxpool layer after Conv1?

### ISSUE THREAD

**Issue by shuzhaolei** [facebookresearch/VMZ#61]
Why there is no maxpool layer after Conv1? 
Based on ResNet, I think it should be a maxpool layer around R2Plus1D/lib/models/r3d_model.py line179. But in your code, I couldn't find one. 

Waiting for your answer, thx!

**Comment by shuzhaolei** [comment]
And I am trying to re-implement your work with PyTorch. I don't know coding differences between PyTorch and Caffe2 exactly.

**Comment by dutran** [comment]
It is a design choice, in later model we use MaxPool but with higher resolution (https://arxiv.org/abs/1904.02811). Code & models are released soon.
