### ISSUE TITLE
dense prediction on ucf101 split1

### ISSUE THREAD

**Issue by malege** [facebookresearch/VMZ#63]
I have finished  fine-tune R(2+1)D-34 model on ucf101 and want to evaluate the fine-tuned model.How can i generate .csv  files include  paths to local files,video_id for each video and also starting frame for each clip  like "hmdb51_test_01_video_id_dense_l32_1.csv" and "kinetics_val_full_video_id_dense_l32_1.csv"? The list files i downloaded  not  include these ucf files.@dutran  Can you help me? Thank you very much!

**Comment by dutran** [comment]
Please use ```test_net_large.py``` instead of dense prediction to save computation.
