### ISSUE TITLE
Error when running the test script

### ISSUE THREAD

**Issue by pchunduri6** [facebookresearch/VMZ#66]
I've been trying to run the test script (test_r2plus1d_kinetics.sh) provided in the scripts folder of the repository to run a pretrained model on the kinetics validation dataset. However, I face the error "dim() called on undefined Tensor" when doing this. I've tried to localize the error and believe that it is being caused in the "workspace.CreateNet" function because the input blobs to this function are empty. However, I am unable to resolve this issue and wanted to know if I am doing anything wrong.
I am using the pretrained_model "r2.5d_d18_l8.pkl" with the kinetics-400-validation dataset to run this model. Any leads will really help. Thanks in advance!

**Comment by HamedSmart** [comment]
Hello, Have you solved the problem? I have got the same problem.

**Comment by dutran** [comment]
This should be fixed now https://github.com/facebookresearch/VMZ/issues/69
