### ISSUE TITLE
Error when running the test script

### ISSUE THREAD

**Issue by HamedSmart** [facebookresearch/VMZ#67]
Hello, thank you very much for your great work. I have faced a problem after successfully building caffe2. When running the test script, I have a problem as follows:
 return func(*args, **kwargs)
RuntimeError: dim() called on undefined Tensor

**Comment by astaileyyoung** [comment]
Is there a solution to this problem or otherwise knowledge of the cause or possible causes? I have had this issue as well despite several attempts following the installation instructions.
