### ISSUE TITLE
doubt in flow data type

### ISSUE THREAD

**Issue by swap2ag** [facebookresearch/VMZ#72]
Hi 
What do **Flow2C**, **Flow3C**, **FlowWithGray** and **FlowWithRGB** mean as **`flow_data_type`** ?

Also, could you please tell me how to run the test code if the flows are already generated?

**Comment by dutran** [comment]
It is explained here https://github.com/pytorch/pytorch/blob/master/caffe2/video/optical_flow.h

**Comment by swap2ag** [comment]
Thanks for the reply.
