### ISSUE TITLE
[E video_decoder.h:269] Error opening video file

### ISSUE THREAD

**Issue by ThatIndianCoder** [facebookresearch/VMZ#85]
For my project, I am trying to use this model. I downloaded all the required packages following the installation guide. Now, I want to test the model for my video dataset. I created an lmdb database of 5 samples from my video dataset by following the "create_video_db.py" script. When I run the script for testing the model, "test_net.py", I get the following error. Could anyone please explain what step I need to take in order to make the model test and train for my dataset?

Following is the output of the script. 

INFO:test_net:Namespace(aggregation=0, batch_size=1, bottleneck_multiplier=1.0, channel_multiplier=1.0, clip_length_of=8, clip_length_rgb=8, clip_per_video=1, conv1_temporal_kernel=3, conv1_temporal_stride=1, crop_per_clip=1, crop_size=112, db_type='pickle', display_iter=10, do_flow_aggregation=0, flow_data_type=0, frame_gap_of=2, gpus=None, input_type=0, load_model_path='/home/ID/Desktop/r2.5d_d18_l8.pkl', model_depth=18, model_name='r2plus1d', multi_label=0, num_channels=3, num_decode_threads=4, num_gpus=1, num_iter=0, num_labels=400, pred_layer_name=None, print_per_class_metrics=0, sampling_rate_of=2, sampling_rate_rgb=1, scale_h=128, scale_w=171, test_data='/home/ID/Desktop/training_data/new_company_training_data', top_k=5, use_convolutional_pred=0, use_cudnn=1, use_dropout=0, use_local_file=1, use_pool1=0, video_res_type=0)
INFO:model_builder:Validated: r2plus1d with 18 layers
INFO:model_builder:with input 8x112x112
INFO:test_net:Running on GPUs: range(0, 1)
INFO:test_net:total_batch_size: 1
WARNING:root:[====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
INFO:data_parallel_model:Parallelizing model for devices: range(0, 1)
INFO:data_parallel_model:Create input and model training operators
WARNING:data_parallel_model:
WARNING:data_parallel_model:############# WARNING #############
WARNING:data_parallel_model:Model video_model_test/<caffe2.python.cnn.CNNModelHelper object at 0x2b9da9eb9290> is used for testing/validation but
WARNING:data_parallel_model:has init_params=True!
WARNING:data_parallel_model:This can conflict with model training.
WARNING:data_parallel_model:Please ensure model = ModelHelper(init_params=False)
WARNING:data_parallel_model:####################################
WARNING:data_parallel_model:
INFO:data_parallel_model:Model for GPU : 0
INFO:model_helper:outputing rgb data
INFO:model_builder:creating r2plus1d, depth=18...
INFO:video_model:in: 64 out: 64
INFO:video_model:in: 64 out: 64
INFO:video_model:in: 64 out: 64
INFO:video_model:in: 64 out: 64
INFO:video_model:in: 64 out: 128
INFO:video_model:in: 128 out: 128
INFO:video_model:in: 128 out: 128
INFO:video_model:in: 128 out: 128
INFO:video_model:in: 128 out: 256
INFO:video_model:in: 256 out: 256
INFO:video_model:in: 256 out: 256
INFO:video_model:in: 256 out: 256
INFO:video_model:in: 256 out: 512
INFO:video_model:in: 512 out: 512
INFO:video_model:in: 512 out: 512
INFO:video_model:in: 512 out: 512
INFO:data_parallel_model:Parameter update function not defined --> only forward
INFO:model_loader:copying conv1_middle_w
INFO:model_loader:copying conv1_middle_spatbn_relu_s
INFO:model_loader:copying conv1_middle_spatbn_relu_b
INFO:model_loader:copying conv1_w
INFO:model_loader:copying conv1_spatbn_relu_s
INFO:model_loader:copying conv1_spatbn_relu_b
INFO:model_loader:copying comp_0_conv_1_middle_w
INFO:model_loader:copying comp_0_spatbn_1_middle_s
INFO:model_loader:copying comp_0_spatbn_1_middle_b
INFO:model_loader:copying comp_0_conv_1_w
INFO:model_loader:copying comp_0_spatbn_1_s
INFO:model_loader:copying comp_0_spatbn_1_b
INFO:model_loader:copying comp_0_conv_2_middle_w
INFO:model_loader:copying comp_0_spatbn_2_middle_s
INFO:model_loader:copying comp_0_spatbn_2_middle_b
INFO:model_loader:copying comp_0_conv_2_w
INFO:model_loader:copying comp_0_spatbn_2_s
INFO:model_loader:copying comp_0_spatbn_2_b
INFO:model_loader:copying comp_1_conv_1_middle_w
INFO:model_loader:copying comp_1_spatbn_1_middle_s
INFO:model_loader:copying comp_1_spatbn_1_middle_b
INFO:model_loader:copying comp_1_conv_1_w
INFO:model_loader:copying comp_1_spatbn_1_s
INFO:model_loader:copying comp_1_spatbn_1_b
INFO:model_loader:copying comp_1_conv_2_middle_w
INFO:model_loader:copying comp_1_spatbn_2_middle_s
INFO:model_loader:copying comp_1_spatbn_2_middle_b
INFO:model_loader:copying comp_1_conv_2_w
INFO:model_loader:copying comp_1_spatbn_2_s
INFO:model_loader:copying comp_1_spatbn_2_b
INFO:model_loader:copying comp_2_conv_1_middle_w
INFO:model_loader:copying comp_2_spatbn_1_middle_s
INFO:model_loader:copying comp_2_spatbn_1_middle_b
INFO:model_loader:copying comp_2_conv_1_w
INFO:model_loader:copying comp_2_spatbn_1_s
INFO:model_loader:copying comp_2_spatbn_1_b
INFO:model_loader:copying comp_2_conv_2_middle_w
INFO:model_loader:copying comp_2_spatbn_2_middle_s
INFO:model_loader:copying comp_2_spatbn_2_middle_b
INFO:model_loader:copying comp_2_conv_2_w
INFO:model_loader:copying comp_2_spatbn_2_s
INFO:model_loader:copying comp_2_spatbn_2_b
INFO:model_loader:copying shortcut_projection_2_w
INFO:model_loader:copying shortcut_projection_2_spatbn_s
INFO:model_loader:copying shortcut_projection_2_spatbn_b
INFO:model_loader:copying comp_3_conv_1_middle_w
INFO:model_loader:copying comp_3_spatbn_1_middle_s
INFO:model_loader:copying comp_3_spatbn_1_middle_b
INFO:model_loader:copying comp_3_conv_1_w
INFO:model_loader:copying comp_3_spatbn_1_s
INFO:model_loader:copying comp_3_spatbn_1_b
INFO:model_loader:copying comp_3_conv_2_middle_w
INFO:model_loader:copying comp_3_spatbn_2_middle_s
INFO:model_loader:copying comp_3_spatbn_2_middle_b
INFO:model_loader:copying comp_3_conv_2_w
INFO:model_loader:copying comp_3_spatbn_2_s
INFO:model_loader:copying comp_3_spatbn_2_b
INFO:model_loader:copying comp_4_conv_1_middle_w
INFO:model_loader:copying comp_4_spatbn_1_middle_s
INFO:model_loader:copying comp_4_spatbn_1_middle_b
INFO:model_loader:copying comp_4_conv_1_w
INFO:model_loader:copying comp_4_spatbn_1_s
INFO:model_loader:copying comp_4_spatbn_1_b
INFO:model_loader:copying comp_4_conv_2_middle_w
INFO:model_loader:copying comp_4_spatbn_2_middle_s
INFO:model_loader:copying comp_4_spatbn_2_middle_b
INFO:model_loader:copying comp_4_conv_2_w
INFO:model_loader:copying comp_4_spatbn_2_s
INFO:model_loader:copying comp_4_spatbn_2_b
INFO:model_loader:copying shortcut_projection_4_w
INFO:model_loader:copying shortcut_projection_4_spatbn_s
INFO:model_loader:copying shortcut_projection_4_spatbn_b
INFO:model_loader:copying comp_5_conv_1_middle_w
INFO:model_loader:copying comp_5_spatbn_1_middle_s
INFO:model_loader:copying comp_5_spatbn_1_middle_b
INFO:model_loader:copying comp_5_conv_1_w
INFO:model_loader:copying comp_5_spatbn_1_s
INFO:model_loader:copying comp_5_spatbn_1_b
INFO:model_loader:copying comp_5_conv_2_middle_w
INFO:model_loader:copying comp_5_spatbn_2_middle_s
INFO:model_loader:copying comp_5_spatbn_2_middle_b
INFO:model_loader:copying comp_5_conv_2_w
INFO:model_loader:copying comp_5_spatbn_2_s
INFO:model_loader:copying comp_5_spatbn_2_b
INFO:model_loader:copying comp_6_conv_1_middle_w
INFO:model_loader:copying comp_6_spatbn_1_middle_s
INFO:model_loader:copying comp_6_spatbn_1_middle_b
INFO:model_loader:copying comp_6_conv_1_w
INFO:model_loader:copying comp_6_spatbn_1_s
INFO:model_loader:copying comp_6_spatbn_1_b
INFO:model_loader:copying comp_6_conv_2_middle_w
INFO:model_loader:copying comp_6_spatbn_2_middle_s
INFO:model_loader:copying comp_6_spatbn_2_middle_b
INFO:model_loader:copying comp_6_conv_2_w
INFO:model_loader:copying comp_6_spatbn_2_s
INFO:model_loader:copying comp_6_spatbn_2_b
INFO:model_loader:copying shortcut_projection_6_w
INFO:model_loader:copying shortcut_projection_6_spatbn_s
INFO:model_loader:copying shortcut_projection_6_spatbn_b
INFO:model_loader:copying comp_7_conv_1_middle_w
INFO:model_loader:copying comp_7_spatbn_1_middle_s
INFO:model_loader:copying comp_7_spatbn_1_middle_b
INFO:model_loader:copying comp_7_conv_1_w
INFO:model_loader:copying comp_7_spatbn_1_s
INFO:model_loader:copying comp_7_spatbn_1_b
INFO:model_loader:copying comp_7_conv_2_middle_w
INFO:model_loader:copying comp_7_spatbn_2_middle_s
INFO:model_loader:copying comp_7_spatbn_2_middle_b
INFO:model_loader:copying comp_7_conv_2_w
INFO:model_loader:copying comp_7_spatbn_2_s
INFO:model_loader:copying comp_7_spatbn_2_b
INFO:model_loader:copying last_out_L400_w
INFO:model_loader:copying last_out_L400_b
INFO:model_loader:copying conv1_middle_spatbn_relu_rm
INFO:model_loader:copying conv1_middle_spatbn_relu_riv
INFO:model_loader:copying conv1_spatbn_relu_rm
INFO:model_loader:copying conv1_spatbn_relu_riv
INFO:model_loader:copying comp_0_spatbn_1_middle_rm
INFO:model_loader:copying comp_0_spatbn_1_middle_riv
INFO:model_loader:copying comp_0_spatbn_1_rm
INFO:model_loader:copying comp_0_spatbn_1_riv
INFO:model_loader:copying comp_0_spatbn_2_middle_rm
INFO:model_loader:copying comp_0_spatbn_2_middle_riv
INFO:model_loader:copying comp_0_spatbn_2_rm
INFO:model_loader:copying comp_0_spatbn_2_riv
INFO:model_loader:copying comp_1_spatbn_1_middle_rm
INFO:model_loader:copying comp_1_spatbn_1_middle_riv
INFO:model_loader:copying comp_1_spatbn_1_rm
INFO:model_loader:copying comp_1_spatbn_1_riv
INFO:model_loader:copying comp_1_spatbn_2_middle_rm
INFO:model_loader:copying comp_1_spatbn_2_middle_riv
INFO:model_loader:copying comp_1_spatbn_2_rm
INFO:model_loader:copying comp_1_spatbn_2_riv
INFO:model_loader:copying comp_2_spatbn_1_middle_rm
INFO:model_loader:copying comp_2_spatbn_1_middle_riv
INFO:model_loader:copying comp_2_spatbn_1_rm
INFO:model_loader:copying comp_2_spatbn_1_riv
INFO:model_loader:copying comp_2_spatbn_2_middle_rm
INFO:model_loader:copying comp_2_spatbn_2_middle_riv
INFO:model_loader:copying comp_2_spatbn_2_rm
INFO:model_loader:copying comp_2_spatbn_2_riv
INFO:model_loader:copying shortcut_projection_2_spatbn_rm
INFO:model_loader:copying shortcut_projection_2_spatbn_riv
INFO:model_loader:copying comp_3_spatbn_1_middle_rm
INFO:model_loader:copying comp_3_spatbn_1_middle_riv
INFO:model_loader:copying comp_3_spatbn_1_rm
INFO:model_loader:copying comp_3_spatbn_1_riv
INFO:model_loader:copying comp_3_spatbn_2_middle_rm
INFO:model_loader:copying comp_3_spatbn_2_middle_riv
INFO:model_loader:copying comp_3_spatbn_2_rm
INFO:model_loader:copying comp_3_spatbn_2_riv
INFO:model_loader:copying comp_4_spatbn_1_middle_rm
INFO:model_loader:copying comp_4_spatbn_1_middle_riv
INFO:model_loader:copying comp_4_spatbn_1_rm
INFO:model_loader:copying comp_4_spatbn_1_riv
INFO:model_loader:copying comp_4_spatbn_2_middle_rm
INFO:model_loader:copying comp_4_spatbn_2_middle_riv
INFO:model_loader:copying comp_4_spatbn_2_rm
INFO:model_loader:copying comp_4_spatbn_2_riv
INFO:model_loader:copying shortcut_projection_4_spatbn_rm
INFO:model_loader:copying shortcut_projection_4_spatbn_riv
INFO:model_loader:copying comp_5_spatbn_1_middle_rm
INFO:model_loader:copying comp_5_spatbn_1_middle_riv
INFO:model_loader:copying comp_5_spatbn_1_rm
INFO:model_loader:copying comp_5_spatbn_1_riv
INFO:model_loader:copying comp_5_spatbn_2_middle_rm
INFO:model_loader:copying comp_5_spatbn_2_middle_riv
INFO:model_loader:copying comp_5_spatbn_2_rm
INFO:model_loader:copying comp_5_spatbn_2_riv
INFO:model_loader:copying comp_6_spatbn_1_middle_rm
INFO:model_loader:copying comp_6_spatbn_1_middle_riv
INFO:model_loader:copying comp_6_spatbn_1_rm
INFO:model_loader:copying comp_6_spatbn_1_riv
INFO:model_loader:copying comp_6_spatbn_2_middle_rm
INFO:model_loader:copying comp_6_spatbn_2_middle_riv
INFO:model_loader:copying comp_6_spatbn_2_rm
INFO:model_loader:copying comp_6_spatbn_2_riv
INFO:model_loader:copying shortcut_projection_6_spatbn_rm
INFO:model_loader:copying shortcut_projection_6_spatbn_riv
INFO:model_loader:copying comp_7_spatbn_1_middle_rm
INFO:model_loader:copying comp_7_spatbn_1_middle_riv
INFO:model_loader:copying comp_7_spatbn_1_rm
INFO:model_loader:copying comp_7_spatbn_1_riv
INFO:model_loader:copying comp_7_spatbn_2_middle_rm
INFO:model_loader:copying comp_7_spatbn_2_middle_riv
INFO:model_loader:copying comp_7_spatbn_2_rm
INFO:model_loader:copying comp_7_spatbn_2_riv
INFO:data_parallel_model:Creating checkpoint synchronization net
INFO:data_parallel_model:Run checkpoint net
[E video_decoder.h:269] Error opening video file RIFFI

#""""""Long lines of unsupported characters follows after this point""""""""""

**Comment by ThatIndianCoder** [comment]
I solved this problem by referring to another closed issue. The solution is to keep both use_list (in create_video_db.py) and use_local_file (test_net.py) to either '1' or '0'. They both should have the same value.

**Comment by dutran** [comment]
Glad to hear you got your issue solved. Thanks for the update.
