### ISSUE TITLE
Missing links

### ISSUE THREAD

**Issue by bjuncek** [facebookresearch/VMZ#87]
Hi all - some links are missing from https://github.com/facebookresearch/VMZ/blob/master/tutorials/model_zoo.md

Specifically, R(2+1)D-34 models pretrained on IG are not there (finetuned are ok).

**Comment by dutran** [comment]
can you tried again? just updated the link. It works for me.

**Comment by sandhawalia** [comment]
Model link works again. @bjuncek Thanks !

**Comment by bjuncek** [comment]
@dutran works now! Cheers.
